server:
  port: 12021

spring:
  application:
    name: config-server
  cloud:
    config:
      label: dev
      server:
        git:
          uri: https://github.com/starriddle/springcloud-starter/
          searchPaths: 'config_repo/{application}'
#          username: username # \u79C1\u6709\u4ED3\u5E93\u9700\u8981\u7528\u6237\u540D\u5BC6\u7801
#          password: password
#          default-label:dev
#  profiles:
#    active: eureka

---
spring:
  profiles: eureka

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:12011/eureka/