server:
  port: 12013

spring:
  application:
    name: eureka-server           # 定义客户端服务名称, 在注册中心注册后，其他服务可通过该名称进行通讯，一般用于客户端

eureka:                           # 注册中心 集群配置
#  instance:
#    hostname: localhost
  client:                         # 注册中心也是一个“客户端”，默认会将自己作为客户端来注册自己，需要修改默认配置：
    register-with-eureka: true    # 1. 默认为true，客户端向注册中心注册本应用，注册中心本身不需要向自己注册，但在集群中可向其他注册中心注册自己
    fetch-registry: true          # 2. 默认为true，客户端向注册中心检索服务，注册中心本身职责就是维护服务实例，不需要去检索，但在集群中可向其他注册中心检索
    serviceUrl:                   # 指定服务注册中心URL，为本身URL，但在集群中应为其他注册中心的URL，多个URL以逗号隔开
      defaultZone: http://localhost:12012/eureka/