server:
  port: 12010

spring:
  application:
    # 定义客户端服务名称, 在注册中心注册后，其他服务可通过该名称进行通讯，一般用于客户端
    name: eureka-server

# 注册中心 单机配置
eureka:
  instance:
    hostname: localhost
  # 注册中心也是一个“客户端”，默认会将自己作为客户端来注册自己，需要修改默认配置：
  client:
    # 客户端向注册中心注册本应用，默认为true
    # 注册中心本身不需要向自己注册
    # 在集群中可向其他注册中心注册自己
    register-with-eureka: false
    # 客户端向注册中心检索服务，默认为true
    # 注册中心本身职责就是维护服务实例，不需要去检索
    # 但在集群中可向其他注册中心检索
    fetch-registry: false
    # 指定服务注册中心URL，单机模式下为本身URL
    # 在集群中应为其他注册中心的URL，多个URL以逗号隔开
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # 注册中心保护机制，默认开启；
    # 当其注册表里服务因为网络或其他原因出现故障而关停时，Eureka不会剔除服务注册，而是等待其修复，
    # Eureka 会统计15分钟之内心跳失败的比例，低于85%将会触发保护机制，不剔除服务提供者，
    # 如果关闭，服务注册中心将不可用的实例立即剔除
    # 生产环境不建议关闭
    enable-self-preservation: true
    # 清理间隔，每隔指定时间自动清理不可用实例（单位毫秒，默认为0，立即清理）
    # 经测试，作用未知，但设置非零值后，开启保护机制，eureka无警告信息
    eviction-interval-timer-in-ms: 180000