server:
  port: 12001 # 设置WebApp端口

spring:
  application:
    name: demo-server # 设置WebApp名称，在spring cloud会被注册为服务名
#  profiles:
#    active: demo2

management: # 配置actuator
  endpoints:
    web:
      exposure:
        include: "*" # 设置通过http可访问的actuator信息，springcloud2.0后默认只有info+health
  server:
    port: 12000 # 设置访问actuator信息的端口，默认与app的端口一致
#    address: 127.0.0.1 # 设置可以访问actuator信息的访客地址，此处设置仅限本地访问，默认无限制

info: # 可自定义actuator/info下的信息，默认没有内置信息
  app:
    name: hello-server
    version: 0.0.1-SNAPSHOT

# @PropertySource注解可加载properties文件配置，yaml文件配置则不可以

# yaml可在单一文件中定义不同环境的配置，使用spring.profiles来定义{profileName}
# properties一个文件只能定义一个环境的配置，使用application-{profileName}.properties
# 可使用spring.profiles.active来指定环境配置
---
### demo2环境配置 ###
 spring:
   profiles: demo2
 server:
   port: 12002 # 针对server2配置：设置WebApp端口，覆盖通用设置
---
### demo3环境配置 ###
 spring:
   profiles: demo3
 server:
   port: 12003 # 针对server3配置：设置WebApp端口，覆盖通用设置