server:
  # 设置WebApp端口
  port: 12001

spring:
  application:
    # 设置WebApp名称
    name: demo-server
  profiles:
    # 指定环境配置
    active: demo3

# 配置actuator
management:
  endpoints:
    web:
      exposure:
        # 设置通过http可访问的actuator信息，springcloud2.0后默认只有info+health
        include: "*"
  server:
    # 设置访问actuator信息的端口，默认与app的端口一致
    port: 12000
    # 设置可以访问actuator信息的访客地址，此处设置仅限本地访问，默认无限制
    address: 127.0.0.1

# 可自定义actuator/info下的信息，默认没有内置信息
info:
  app:
    name: hello-server
    version: 2019.03.15-SNAPSHOT

# ##############################################################################
#
# @PropertySource注解可加载properties文件配置，yaml文件配置则不可以
#
# properties一个文件只能定义一个环境的配置，使用application-{profileName}.properties
#
# yaml可在单一文件中定义不同环境的配置，使用spring.profiles来定义{profileName}
#
# 可使用spring.profiles.active来指定环境配置
# ##############################################################################

---
### demo2环境配置 ###
spring:
  # 环境配置名称 demo2
  profiles: demo2
  application:
    # 针对demo2配置：设置WebApp名称，覆盖通用设置
    name: demo2-server

server:
  # 针对demo2配置：设置WebApp端口，覆盖通用设置
  port: 12002

---
### demo3环境配置 ###
spring:
  application:
    # 针对demo3配置：设置WebApp名称，覆盖通用设置
    name: demo3-server
  # 环境配置名称 demo3，不要求必须在第一行
  profiles: demo3

server:
  # 针对server3配置：设置WebApp端口，覆盖通用设置
  port: 12003
