server:
  port: 12021 # 设置WebApp端口

spring:
  application:
    name: demo # 设置WebApp名称，在spring cloud会被注册为服务名
#  profiles:
#    active: server2

eureka:
  instance:
    lease-renewal-interval-in-seconds: 60 # 租期更新时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 180 # 租期到期时间（默认90秒）
    prefer-ip-address: true # 设置以Ip地址形式来定义注册中心显示的本服务地址，默认false，以主机名形式
#    virtual-host-name: helloworld
  client:
    registry-fetch-interval-seconds: 60 #间隔多久去拉取服务注册信息，默认为30秒
    service-url:
      defaultZone: http://localhost:12001/eureka/ # 单个注册中心配置
#      defaultZone: http://localhost:12002/eureka/,http://localhost:12003/eureka/ # 注册中心集群配置

management:
  endpoints:
    web:
      exposure:
        include: "*" # 设置通过http可访问的actuator信息，springcloud2.0后默认只有info+health
  server:
    port: 12020 # 设置访问actuator信息的端口，默认与app的端口一致
#    address: 127.0.0.1 # 设置可以访问actuator信息的访客地址，此处设置仅限本地访问，默认无限制

info: # 可自定义actuator/info下的信息，默认没有内置信息
  app:
    name: hello-server
    version: 0.0.1-SNAPSHOT

# @PropertySource注解可加载properties文件配置，yaml文件配置则不可以

# yaml可在单一文件中定义不同环境的配置，使用spring.profiles来定义{profileName}
# properties一个文件只能定义一个环境的配置，使用application-{profileName}.properties
# 可使用spring.profiles.active来指定环境配置
---
### server2环境配置 ###
 spring:
   profiles: server2
 server:
   port: 12022 # 针对server2配置：设置WebApp端口，覆盖通用设置
---
### server3环境配置 ###
 spring:
   profiles: server3
 server:
   port: 12023 # 针对server3配置：设置WebApp端口，覆盖通用设置