server:
  port: 12001

spring:
  application:
    name: admin-client

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:12010/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

info:
  app:
    name: spring-cloud-admin-client
    version: 2019.03.15-SNAPSHOT