spring:
  profiles:
    active: clientA

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:12010/eureka/

---
spring:
  profiles: clientA
  application:
    name: client-A

server:
  port: 12001
#  servlet:
    # 如设置context-path，路由转发时需要在请求路径中带上context-path
#    context-path: /serverA


---
spring:
  profiles: clientB
  application:
    name: client-B

server:
  port: 12002
#  servlet:
#    context-path: /serverB
